#!/usr/bin/env node
/** Apply DiagramWeave's adaptive contextual-orchestrator request default. */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const expectedBranch = 'agent/adaptive-orchestrator-default';
const branch = process.env.GITHUB_REF_NAME ?? expectedBranch;
if (branch !== expectedBranch) {
  throw new Error(`refusing to mutate unexpected branch: ${branch}`);
}

function replaceOnce(text, oldText, newText, label) {
  const parts = text.split(oldText);
  if (parts.length !== 2) {
    throw new Error(`${label}: expected one match, found ${parts.length - 1}`);
  }
  return `${parts[0]}${newText}${parts[1]}`;
}

const sourcePath = resolve(
  root,
  'packages/contextual-orchestrator/src/client.js',
);
let source = readFileSync(sourcePath, 'utf8');
source = replaceOnce(
  source,
  `            model: normalized.model,\n            messages,`,
  `            model: normalized.model,\n            orchestration_mode: 'auto',\n            messages,`,
  'adaptive request field',
);
writeFileSync(sourcePath, source);

const testPath = resolve(
  root,
  'packages/contextual-orchestrator/test/client.test.js',
);
let tests = readFileSync(testPath, 'utf8');
tests = replaceOnce(
  tests,
  `  assert.equal(body.model, 'contextual-orchestrator');\n  assert.equal(body.temperature, 0);`,
  `  assert.equal(body.model, 'contextual-orchestrator');\n  assert.equal(body.orchestration_mode, 'auto');\n  assert.equal(body.temperature, 0);`,
  'request contract assertion',
);
tests = replaceOnce(
  tests,
  `  assert.equal(JSON.parse(observedOptions.body).model, 'contextual-orchestrator');\n`,
  `  const body = JSON.parse(observedOptions.body);\n  assert.equal(body.model, 'contextual-orchestrator');\n  assert.equal(body.orchestration_mode, 'auto');\n`,
  'default options assertion',
);
writeFileSync(testPath, tests);

const changelogPath = resolve(root, 'CHANGELOG.md');
let changelog = readFileSync(changelogPath, 'utf8');
changelog = replaceOnce(
  changelog,
  '### Changed\n\n',
  '### Changed\n\n- Contextual Orchestrator edit-proposal requests now explicitly use `orchestration_mode: "auto"`, allowing the orchestration plane to select the least-cost quality-sufficient single route, verification, or conducted workflow while DiagramWeave retains strict local proposal validation.\n',
  'changelog',
);
writeFileSync(changelogPath, changelog);

const adrPath = resolve(
  root,
  'docs/adr/0008-adaptive-orchestrator-default.md',
);
if (existsSync(adrPath)) {
  throw new Error(`refusing to replace existing ADR: ${adrPath}`);
}
writeFileSync(
  adrPath,
  `# ADR-0008: Adaptive contextual-orchestrator mode for edit proposals\n\n- Status: Accepted\n- Date: 2026-08-15\n\n## Context\n\nThe adapter previously omitted an orchestration policy field. Omission currently resolves to the gateway default, but that implicit behavior is easy to regress and does not make the product contract reviewable. DiagramWeave should specify the adaptive policy without independently choosing one model or a fixed multi-agent topology.\n\n## Decision\n\nEvery production edit-proposal request includes \\`orchestration_mode: "auto"\\`.\n\n- contextual-orchestrator owns model/provider selection, reasoning effort, verification, workflow depth, and known-cost optimization;\n- DiagramWeave owns the source-first prompt, revision binding, requested/effective scope, strict JSON extraction, and \\`validateEditProposal\\`;\n- no provider response-format feature may bypass the adaptive orchestration path;\n- explicit modes remain available only for controlled evaluation and operator override, not as the client default.\n\n## Consequences\n\nThe request contract is explicit and test-protected. A response can be generated by one or several orchestration steps, but it must still pass the same deterministic DiagramWeave Core validation before it can become a proposal.\n\n## References\n\nOmidvar, H., & Akhlaghi, V. (2026). *A communication-theoretic framework for LLM agents: Cost-aware adaptive reliability* [Preprint]. arXiv. https://doi.org/10.48550/arXiv.2605.09121\n\nTang, Y., Cetin, E., Xu, J., Sun, Q., Nielsen, S., Richard, V., Goda, H., Tymchenko, I., Nguyen, N., Lee, H., Ashiga, M., Kotyan, S., Kuroki, S., & Clanuwat, T. (2026). *Sakana Fugu technical report* [Technical report]. arXiv. https://doi.org/10.48550/arXiv.2606.21228\n`,
  'utf8',
);
